server:
  port: 8800
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/*/mapper/xml/*.xml
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guigu-oa?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 510963
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  activiti:
    async-executor-activate : false
    database-schema-update: true
    db-history-used: true
    history-level: full
    check-process-definitions: true
wechat:
  mpAppId: wxda05b02486d6f731
  mpAppSecret: 6796444e635a79255a3f5652ef0f4d20
  userInfoUrl: http://ggkt2.vipgz1.91tunnel.com/admin/wechat/userInfo